import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';

import { renderConfigYaml } from './config.js';
import {
  SYNCHRONIZATION_NOTICE_FILENAME,
  SYNCHRONIZATION_NOTICE_MARKER,
} from './constants.js';
import { configDir, configPath, noticePath } from './layout.js';
import { pathExists } from './paths.js';
import type { Config, StatusFile } from './types.js';

async function readIfExists(file: string): Promise<string | undefined> {
  try {
    return await readFile(file, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw error;
    }
    return undefined;
  }
}

/** Writes `<destination>/.gsynchro/gsynchro.yml`; returns whether it changed. */
export async function writeConfigurationMirror(
  destination: string,
  cfg: Config,
): Promise<boolean> {
  const mirrorPath = configPath(destination);
  const content = renderConfigYaml(cfg);

  if (await readIfExists(mirrorPath) === content) {
    return false;
  }

  await mkdir(configDir(destination), { recursive: true });
  const temporary = `${mirrorPath}.tmp-${process.pid}`;
  await writeFile(temporary, content, 'utf8');
  await rename(temporary, mirrorPath);
  return true;
}

export function renderSynchronizationNotice(cfg: Config): string {
  const extensions = cfg.extensions
    .map((extension) => `- \`${extension}\``)
    .join('\n');
  const items = cfg.items
    .map((item) => `- \`${item}\``)
    .join('\n');

  return `${SYNCHRONIZATION_NOTICE_MARKER}
# gsynchro synchronization notice

This file is generated by gsynchro from the repository configuration. Do not edit it: gsynchro replaces it when the configuration changes. It describes the configured scope; it does **not** confirm that a gsynchro process is currently running.

## What is synchronized

A file is synchronized only when both its path and extension match the rules below.

Maximum file size: **${cfg.maxFileSizeMiB} MiB**.

### Eligible extensions

${extensions}

### Selected paths

${items}

## Working from this folder

Files created here outside these paths, or with an extension not listed above, remain in this folder only and are not copied into the repository. To include them, update \`.gsynchro/gsynchro.yml\` in the repository and run gsynchro again.

Use this folder for shared project context. Source code, build output, runtime data, and other files outside the configured scope are intentionally not synchronized.
`;
}

/** Writes `<destination>/GSYNCHRO.md`; returns whether it changed. */
export async function writeSynchronizationNotice(
  destination: string,
  cfg: Config,
): Promise<boolean> {
  const file = noticePath(destination);
  const content = renderSynchronizationNotice(cfg);
  const existing = await readIfExists(file);

  if (
    existing !== undefined &&
    !existing.includes(SYNCHRONIZATION_NOTICE_MARKER)
  ) {
    throw new Error(
      `${SYNCHRONIZATION_NOTICE_FILENAME} already exists in the destination and is not managed by gsynchro; rename or move it before starting gsynchro.`,
    );
  }

  if (existing === content) {
    return false;
  }

  await writeFile(file, content, 'utf8');
  return true;
}

/** Whether gsynchro has left its markers in the destination before. */
export async function isDestinationInitialized(destination: string): Promise<boolean> {
  return (
    await pathExists(configDir(destination)) ||
    await pathExists(noticePath(destination))
  );
}

/*
 * An unmounted rclone/FUSE mount point is an ordinary empty directory: it
 * passes every existence check, and a scan of it would report every file
 * as deleted on the destination. Once a synchronization has been recorded,
 * require gsynchro's own markers (the `.gsynchro/` mirror directory or the
 * GSYNCHRO.md notice) to be present before trusting the destination.
 */
export async function assertDestinationInitialized(
  destination: string,
  previousStatus: StatusFile,
): Promise<void> {
  const hasSynchronizedBefore = Object.values(previousStatus.files)
    .some((entry) => entry.drive !== null);

  if (!hasSynchronizedBefore || await isDestinationInitialized(destination)) {
    return;
  }

  throw new Error(
    `Destination ${destination} has neither .gsynchro/ nor ${SYNCHRONIZATION_NOTICE_FILENAME}, ` +
    'although files were synchronized before. It looks unmounted or replaced; ' +
    'refusing to treat its missing files as deletions. Mount it again, or run ' +
    '`gsynchro --setup` if this really is the intended destination.',
  );
}
